export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS";
export const GET_CONVERSATIONS_FAILED = "GET_CONVERSATIONS_FAILED";
export const ADD_CONVERSATION_STORE = "ADD_CONVERSATION_STORE";
export const ADD_CONVERSATION_DB_SUCCESS = "ADD_CONVERSATION_DB_SUCCESS";
export const ADD_CONVERSATION_DB_FAILED = "ADD_CONVERSATION_DB_FAILED";
export const UPDATE_CONVERSATION_SUCCESS = "UPDATE_CONVERSATION_SUCCESS";
export const UPDATE_CONVERSATION_FAILED = "UPDATE_CONVERSATION_FAILED";

export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS"
export const CREATE_TWEET_FAILED = "CREATE_TWEET_FAILED"
export const GET_TWEETS_SUCCESS = "GET_TWEETS_SUCCESS"
export const GET_TWEETS_FAILED = "GET_TWEETS_FAILED"
export const DELETE_TWEET_SUCCESS = "DELETE_TWEET_SUCCESS"
export const DELETE_TWEET_FAILED = "DELETE_TWEET_FAILED"
export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS"
export const LIKE_TWEET_FAILED = "LIKE_TWEET_FAILED"
export const UNLIKE_TWEET_SUCCESS = "UNLIKE_TWEET_SUCCESS"
export const UNLIKE_TWEET_FAILED = "UNLIKE_TWEET_FAILED"
export const BOOKMARK_TWEET_SUCCESS = "BOOKMARK_TWEET_SUCCESS"
export const BOOKMARK_TWEET_FAILED = "BOOKMARK_TWEET_FAILED"
export const UNBOOKMARK_TWEET_SUCCESS = "UNBOOKMARK_TWEET_SUCCESS"
export const UNBOOKMARK_TWEET_FAILED = "UNBOOKMARK_TWEET_FAILED"
export const RETWEET_TWEET_SUCCESS = "RETWEET_TWEET_SUCCESS"
export const RETWEET_TWEET_FAILED = "RETWEET_TWEET_FAILED"
export const UNRETWEET_TWEET_SUCCESS = "UNRETWEET_TWEET_SUCCESS"
export const UNRETWEET_TWEET_FAILED = "UNRETWEET_TWEET_FAILED"
export const REPLY_TWEET_SUCCESS = "REPLY_TWEET_SUCCESS"
export const REPLY_TWEET_FAILED = "REPLY_TWEET_FAILED"

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILED = "GET_PROFILE_FAILED";
export const PROFILE_INPUT_CHANGE_HANDLER = "PROFILE_INPUT_CHANGE_HANDLER";
export const PROFILE_IMAGE_CHANGE_HANDLER = "PROFILE_IMAGE_CHANGE_HANDLER";
export const UPDATE_PROFILE_SUCCESS= "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILED= "UPDATE_PROFILE_FAILED";

export const DELETE_PROFILE_SUCCESS= "DELETE_PROFILE_SUCCESS";
export const DELETE_PROFILE_FAILED= "DELETE_PROFILE_FAILED";