export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS";
export const GET_CONVERSATIONS_FAILED = "GET_CONVERSATIONS_FAILED";
export const ADD_CONVERSATION_STORE = "ADD_CONVERSATION_STORE";
export const ADD_CONVERSATION_DB_SUCCESS = "ADD_CONVERSATION_DB_SUCCESS";
export const ADD_CONVERSATION_DB_FAILED = "ADD_CONVERSATION_DB_FAILED";
export const UPDATE_CONVERSATION_SUCCESS = "UPDATE_CONVERSATION_SUCCESS";
export const UPDATE_CONVERSATION_FAILED = "UPDATE_CONVERSATION_FAILED";

export const CREATE_TWEET_SUCCESS = "CREATE_TWEET_SUCCESS"
export const CREATE_TWEET_FAILED = "CREATE_TWEET_FAILED"
export const GET_TWEETS_SUCCESS = "GET_TWEETS_SUCCESS"
export const GET_TWEETS_FAILED = "GET_TWEETS_FAILED"
export const DELETE_TWEET_SUCCESS = "DELETE_TWEET_SUCCESS"
export const DELETE_TWEET_FAILED = "DELETE_TWEET_FAILED"
export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS"
export const LIKE_TWEET_FAILED = "LIKE_TWEET_FAILED"
export const UNLIKE_TWEET_SUCCESS = "UNLIKE_TWEET_SUCCESS"
export const UNLIKE_TWEET_FAILED = "UNLIKE_TWEET_FAILED"