export const GET_CONVERSATIONS_SUCCESS = "GET_CONVERSATIONS_SUCCESS";
export const GET_CONVERSATIONS_FAILED = "GET_CONVERSATIONS_FAILED";
export const ADD_CONVERSATION_STORE = "ADD_CONVERSATION_STORE";
export const ADD_CONVERSATION_DB_SUCCESS = "ADD_CONVERSATION_DB_SUCCESS";
export const ADD_CONVERSATION_DB_FAILED = "ADD_CONVERSATION_DB_FAILED";
export const UPDATE_CONVERSATION_SUCCESS = "UPDATE_CONVERSATION_SUCCESS";
export const UPDATE_CONVERSATION_FAILED = "UPDATE_CONVERSATION_FAILED";